# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "DawnNav"
license = "MIT"
licenselink = "https://github.com/oulh/hugo-webstack/blob/master/LICENSE"
description = "a theme for website navigation, it's based on webstack. "
homepage = "https://dawnnav.pages.dev/"
tags = ["url", "navigation", "webstack","communism","marxism","marx","lenin","USSR","left wing","maoism","maoist","毛主义"]
features = ["minimalism", "simple"]
min_version = "0.116.1"

[author]
  name = "DawnNav"
  homepage = "https://dawnnav.pages.dev/"

# If porting an existing theme
[original]
  name = "webstack-hugo"
  homepage = "https://iplaycode.github.io/nav/"
  repo = "https://github.com/iplaycode/webstack-hugo/tree/5e85297db430079c468dd33e78a945556973c73a/"
